# .github/workflows/ci.yml
name: Scala CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Scala environment
      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          scala-version: '2.13.8'

      # Install sbt
      - name: Install sbt
        run: |
          echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
          sudo apt update
          sudo apt install sbt

      # Compile and test the code using sbt
      - name: Run tests
        run: sbt test
